export default {
  INCLUDE_ITEM: 'LANCHE_INCLUDE_ITEM',
  REMOVE_ITEM: 'LANCHE_REMOVE_ITEM',
  SELECT: 'LANCHE_SELECT',
  FETCH: 'LANCHE_FETCH',
  FETCHED: 'LANCHE_FETCHED',
  ERROR: 'LANCHE_ERROR',
  DONE: 'LANCHE_DONE',
};
